var NUM_MON_TYPES = 4;
var monsterTable:Array = new Array();
monsterTable[0] = new Array();
monsterTable[1] = new Array();
monsterTable[2] = new Array();
monsterTable[3] = new Array();
monsterTable[4] = new Array();

monsterTable[0][0] = 		"TEST ENEMY"; 		//name
monsterTable[0][1] =		20;	//hp
monsterTable[0][2] =		"enemy";				//graphic
monsterTable[0][3] =		"I am dumb.";
monsterTable[0][4] =		10; //xp
monsterTable[0][5] =		"Warrior"; //AI type
monsterTable[0][6] =		2; //minimum damage
monsterTable[0][7] =		5; //max damage
monsterTable[0][8] =		0; //fire resist
monsterTable[0][9] =		0; //frost resist
monsterTable[0][10] =		0; //holy resist
monsterTable[0][11] =		0; //nature resist
monsterTable[0][12] =		0; //shadow resist
monsterTable[0][13] =		30;	//attack range

monsterTable[1][0] = 		"STRONG ENEMY"; 		//name
monsterTable[1][1] =		50;	//hp
monsterTable[1][2] =		"enemy";				//graphic
monsterTable[1][3] =		"I am stronger.";
monsterTable[1][4] =		50; //xp
monsterTable[1][5] =		"Idle"; //AI type
monsterTable[1][6] =		2; //minimum damage
monsterTable[1][7] =		5; //max damage
monsterTable[1][8] =		0; //fire resist
monsterTable[1][9] =		0; //frost resist
monsterTable[1][10] =		0; //holy resist
monsterTable[1][11] =		0; //nature resist
monsterTable[1][12] =		0; //shadow resist
monsterTable[1][13] =		30;	//attack range

monsterTable[2][0] = 		"Bogling"; 				//name
monsterTable[2][1] =		50;						//hp
monsterTable[2][2] =		"bogling";				//graphic
monsterTable[2][3] =		"Nature Resistant";
monsterTable[2][4] =		50; 					//xp
monsterTable[2][5] =		"Wildlife"; 			//AI type
monsterTable[2][6] =		1; 						//minimum damage
monsterTable[2][7] =		2;						 //max damage
monsterTable[2][8] =		0; //fire resist
monsterTable[2][9] =		0; //frost resist
monsterTable[2][10] =		0; //holy resist
monsterTable[2][11] =		10; //nature resist
monsterTable[2][12] =		0; //shadow resist
monsterTable[2][13] =		30;	//attack range

monsterTable[3][0] = 		"Lord Bennidy"; 				//name
monsterTable[3][1] =		250;						//hp
monsterTable[3][2] =		"lord";				//graphic
monsterTable[3][3] =		"Lord of Undead";
monsterTable[3][4] =		250; 					//xp
monsterTable[3][5] =		"Warrior"; 			//AI type
monsterTable[3][6] =		10; 						//minimum damage
monsterTable[3][7] =		15;						 //max damage
monsterTable[3][8] =		0; //fire resist
monsterTable[3][9] =		0; //frost resist
monsterTable[3][10] =		90; //holy resist
monsterTable[3][11] =		0; //nature resist
monsterTable[3][12] =		0; //shadow resist
monsterTable[3][13] =		30;	//attack range

monsterTable[4][0] = 		"Spearman"; 			//name
monsterTable[4][1] =		30;						//hp
monsterTable[4][2] =		"spearman";				//graphic
monsterTable[4][3] =		"Long Attack Range";
monsterTable[4][4] =		5; 					//xp
monsterTable[4][5] =		"Wildlife"; 			//AI type
monsterTable[4][6] =		1; 						//minimum damage
monsterTable[4][7] =		2;						//max damage
monsterTable[4][8] =		0; //fire resist
monsterTable[4][9] =		0; //frost resist
monsterTable[4][10] =		0; //holy resist
monsterTable[4][11] =		0; //nature resist
monsterTable[4][12] =		0; //shadow resist
monsterTable[4][13] =		50;	//attack range